src/Entity/Batch.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BatchRepository")
 */
class Batch
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateAcquired;

    /**
     * @ORM\Column(type="float")
     */
    private $costPerBird;

    /**
     * @ORM\Column(type="integer")
     */
    private $numberOfSpecimens;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $supplier;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Expense", mappedBy="batch")
     */
    private $expenses;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Income", mappedBy="batch")
     */
    private $incomes;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="batches")
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Farm", inversedBy="batches")
     */
    private $farm;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateSoldOut;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $onSale;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $sellingprice;

    public function __construct()
    {
        $this->expenses = new ArrayCollection();
        $this->incomes = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateAcquired(): ?\DateTimeInterface
    {
        return $this->dateAcquired;
    }

    public function setDateAcquired(\DateTimeInterface $dateAcquired): self
    {
        $this->dateAcquired = $dateAcquired;

        return $this;
    }

    public function getCostPerBird(): ?float
    {
        return $this->costPerBird;
    }

    public function setCostPerBird(float $costPerBird): self
    {
        $this->costPerBird = $costPerBird;

        return $this;
    }

    public function getTotalDucks(): ?int
    {
        return $this->getNumberOfSpecimens();
    }

    public function getTotalAcquireCost(): ?float
    {
        return ($this->getNumberOfSpecimens()) * $this->getCostPerBird();
    }

    public function getSupplier(): ?string
    {
        return $this->supplier;
    }

    public function setSupplier(?string $supplier): self
    {
        $this->supplier = $supplier;

        return $this;
    }

    public function getAge()
    {
        if ($this->getDateSoldOut()) {
            return date_diff($this->getDateAcquired(), $this->getDateSoldOut(), true)->format('%R%a');
        }
        return date_diff($this->getDateAcquired(),new \DateTime(), true)->format('%R%a');
    }

    /**
     * @return Collection|Expense[]
     */
    public function getExpenses(): Collection
    {
        return $this->expenses;
    }

    public function getTotalExpenses()
    {
        $total = 0;
        foreach ($this->expenses as $expense) {
            $total += $expense->getAmount();
        }
        return $total;
    }

    public function addExpense(Expense $expense): self
    {
        if (!$this->expenses->contains($expense)) {
            $this->expenses[] = $expense;
            $expense->setBatch($this);
        }

        return $this;
    }

    public function removeExpense(Expense $expense): self
    {
        if ($this->expenses->contains($expense)) {
            $this->expenses->removeElement($expense);
            // set the owning side to null (unless already changed)
            if ($expense->getBatch() === $this) {
                $expense->setBatch(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Income[]
     */
    public function getIncomes(): Collection
    {
        return $this->incomes;
    }

    public function addIncome(Income $income): self
    {
        if (!$this->incomes->contains($income)) {
            $this->incomes[] = $income;
            $income->setBatch($this);
        }

        return $this;
    }

    public function removeIncome(Income $income): self
    {
        if ($this->incomes->contains($income)) {
            $this->incomes->removeElement($income);
            // set the owning side to null (unless already changed)
            if ($income->getBatch() === $this) {
                $income->setBatch(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getFarm(): ?Farm
    {
        return $this->farm;
    }

    public function setFarm(?Farm $farm): self
    {
        $this->farm = $farm;

        return $this;
    }

    public function getDateSoldOut(): ?\DateTimeInterface
    {
        return $this->dateSoldOut;
    }

    public function setDateSoldOut(?\DateTimeInterface $dateSoldOut): self
    {
        $this->dateSoldOut = $dateSoldOut;

        return $this;
    }

    public function getOnSale(): ?bool
    {
        return $this->onSale;
    }

    public function setOnSale(?bool $onSale): self
    {
        $this->onSale = $onSale;

        return $this;
    }

    public function getSellingprice(): ?int
    {
        return $this->sellingprice;
    }

    public function setSellingprice(?int $sellingprice): self
    {
        $this->sellingprice = $sellingprice;

        return $this;
    }

    public function getNumberOfSpecimens(): ?int
    {
        return $this->numberOfSpecimens;
    }

    public function setNumberOfSpecimens(int $numberOfSpecimens): self
    {
        $this->numberOfSpecimens = $numberOfSpecimens;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Controller\Admin\BatchCrudController;
use App\Controller\Admin\FarmCrudController;
use App\Repository\FarmRepository;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(FarmRepository $farmRepo, AdminUrlGenerator $adminUrlGenerator)
    {
        $newfarmurl = $adminUrlGenerator->setController(FarmCrudController::class)->setAction(Action::NEW)->generateUrl();
        $newbatchurl = $adminUrlGenerator->setController(BatchCrudController::class)->setAction(Action::NEW)->generateUrl();
        if ($this->getUser()) {
            // $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
            return $this->render('default/index.html.twig', [
                'farms' => $farmRepo->findBy([
                    'owner' => $this->getUser(),
                ]),
                'newfarm' => $newfarmurl,
                'newbatch' => $newbatchurl,
            ]);
        } else {
            return $this->redirectToRoute('market_index');
        }
    }
}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome{% endblock %}

{% block body %}
{% if app.user %}
<div class="container">
    <div class="row py-3 mb-2">
        <div class="col-sm-12">
            <div class="btn-group">
                <a class="btn btn-info" href="{{newfarm}}" role="button">Add Farm</a>
                <a class="btn btn-warning" href="{{newbatch}}" role="button">Add Batch</a>
            </div>
        </div>
        <div class="col-sm-12">
            {% for farm in farms %}
            <p class="h1 display-4">{{ farm.name }}</p>
            <p class="text-secondary">{{ farm.location }}</p>
            <div class="card-columns">
                {% for batch in farm.batches %}
                    <a href="{{path('batch_show',{ id: batch.id })}}" class="text-info">
                    <div class="card p-2 m-1 {{ batch.dateSoldOut ? 'border-danger text-danger' : batch.onSale ? 'border-success text-success' : 'bg-dark'}}">
                        <div class="card-header">
                            <span class="lead card-title">{{batch.name}}</span>
                            {% if batch.dateSoldOut %}
                                <span class="badge badge-pill badge-danger float-right">sold out</span>
                            {% elseif batch.age > 35 or batch.onSale %}
                                <span class="badge badge-pill badge-success float-right">on sale</span>
                            {% else %}
                                <span class="badge badge-pill badge-warning float-right">sale pending</span>
                            {% endif %}
                        </div>
                        <div class="card-body">
                            <div class="card-text">
                                <p class="h5">{{batch.numberOfSpecimens}} {{batch.category|default('birds')}}</p> 
                                <p class="small">{{(batch.age/7)|round(1, 'ceil') ~ ' weeks ' ~ batch.category}}</p>
                            </div>
                        </div>
                    </div>
                    </a>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
{% endblock %}